# runtime: nodejs
# env: flex
runtime: nodejs10
service: staging
# instance_class: F2
# env: flex
# resources:
#   memory_gb: 4

# automatic_scaling:
#   min_num_instances: 2
#   max_num_instances: 20
#   cpu_utilization:
#     target_utilization: 0.75